-- RODAR SEGUNDO
DROP FUNCTION IF EXISTS insert_property(UUID, VARCHAR, VARCHAR, JSONB, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS insert_property(UUID, VARCHAR, VARCHAR, JSONB, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
